# Generated by Django 3.2 on 2021-05-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_photos'),
        ),
    ]
